//
// Generated file, do not edit! Created by opp_msgc 4.5 from src/node/communication/routing/lbcRouting/LbcRoutingPacket.msg.
//

#ifndef _LBCROUTINGPACKET_M_H_
#define _LBCROUTINGPACKET_M_H_

#include <omnetpp.h>

// opp_msgc version check
#define MSGC_VERSION 0x0405
#if (MSGC_VERSION!=OMNETPP_VERSION)
#    error Version mismatch! Probably this file was generated by an earlier version of opp_msgc: 'make clean' should help.
#endif

// cplusplus {{
#include "RoutingPacket_m.h"
// }}



/**
 * Enum generated from <tt>src/node/communication/routing/lbcRouting/LbcRoutingPacket.msg</tt> by opp_msgc.
 * <pre>
 * enum LbcRoutingPacket_Type
 * {
 * 	LBC_ROUTING_ADV_PACKET 	              = 1;		
 * 	LBC_ROUTING_JOIN_PACKET 	          = 2;		
 * 	LBC_ROUTING_TDMA_PACKET 	          = 3;		
 * 	LBC_ROUTING_DATA_PACKET 	          = 4;
 * 	LBC_ROUTING_COMPETECH_PACKET          = 5;
 * 	LBC_ROUTING_FINALHEAD_PACKET          = 6;
 * 	LBC_ROUTING_QUITELECTION_PACKET       = 7;
 * 	LBC_ROUTING_ADJACENTCH_PACKET         = 8;
 * 	LBC_ROUTING_AGGREGATEDADJACENT_PACKET = 9;
 * 	LBC_ROUTING_ROTAT_TDMA_PACKET         = 10;
 * 	LBC_ROUTING_BS_PACKET                 = 11;
 * 	LBC_ROUTING_BROADCAST_BS_PACKET		  = 12;
 * 	LBC_ROUTING_AGGREGATED_BS_PACKET      = 13;
 * 	
 * };
 * </pre>
 */
enum LbcRoutingPacket_Type {
    LBC_ROUTING_ADV_PACKET = 1,
    LBC_ROUTING_JOIN_PACKET = 2,
    LBC_ROUTING_TDMA_PACKET = 3,
    LBC_ROUTING_DATA_PACKET = 4,
    LBC_ROUTING_COMPETECH_PACKET = 5,
    LBC_ROUTING_FINALHEAD_PACKET = 6,
    LBC_ROUTING_QUITELECTION_PACKET = 7,
    LBC_ROUTING_ADJACENTCH_PACKET = 8,
    LBC_ROUTING_AGGREGATEDADJACENT_PACKET = 9,
    LBC_ROUTING_ROTAT_TDMA_PACKET = 10,
    LBC_ROUTING_BS_PACKET = 11,
    LBC_ROUTING_BROADCAST_BS_PACKET = 12,
    LBC_ROUTING_AGGREGATED_BS_PACKET = 13
};

/**
 * Class generated from <tt>src/node/communication/routing/lbcRouting/LbcRoutingPacket.msg</tt> by opp_msgc.
 * <pre>
 * packet LbcRoutingPacket extends RoutingPacket
 * {	
 * 	int LbcRoutingPacketKind enum (LbcRoutingPacket_Type);   
 * 	int schedule[];	
 * 	double x;
 * 	double y;
 * 	double Tn;
 * 	double RComp;
 * 	double ResidualEnergy;
 * 	double BSDistance;
 * };
 * </pre>
 */
class LbcRoutingPacket : public ::RoutingPacket
{
  protected:
    int LbcRoutingPacketKind_var;
    int *schedule_var; // array ptr
    unsigned int schedule_arraysize;
    double x_var;
    double y_var;
    double Tn_var;
    double RComp_var;
    double ResidualEnergy_var;
    double BSDistance_var;

  private:
    void copy(const LbcRoutingPacket& other);

  protected:
    // protected and unimplemented operator==(), to prevent accidental usage
    bool operator==(const LbcRoutingPacket&);

  public:
    LbcRoutingPacket(const char *name=NULL, int kind=0);
    LbcRoutingPacket(const LbcRoutingPacket& other);
    virtual ~LbcRoutingPacket();
    LbcRoutingPacket& operator=(const LbcRoutingPacket& other);
    virtual LbcRoutingPacket *dup() const {return new LbcRoutingPacket(*this);}
    virtual void parsimPack(cCommBuffer *b);
    virtual void parsimUnpack(cCommBuffer *b);

    // field getter/setter methods
    virtual int getLbcRoutingPacketKind() const;
    virtual void setLbcRoutingPacketKind(int LbcRoutingPacketKind);
    virtual void setScheduleArraySize(unsigned int size);
    virtual unsigned int getScheduleArraySize() const;
    virtual int getSchedule(unsigned int k) const;
    virtual void setSchedule(unsigned int k, int schedule);
    virtual double getX() const;
    virtual void setX(double x);
    virtual double getY() const;
    virtual void setY(double y);
    virtual double getTn() const;
    virtual void setTn(double Tn);
    virtual double getRComp() const;
    virtual void setRComp(double RComp);
    virtual double getResidualEnergy() const;
    virtual void setResidualEnergy(double ResidualEnergy);
    virtual double getBSDistance() const;
    virtual void setBSDistance(double BSDistance);
};

inline void doPacking(cCommBuffer *b, LbcRoutingPacket& obj) {obj.parsimPack(b);}
inline void doUnpacking(cCommBuffer *b, LbcRoutingPacket& obj) {obj.parsimUnpack(b);}


#endif // _LBCROUTINGPACKET_M_H_
