//
// Generated file, do not edit! Created by opp_msgc 4.5 from src/node/communication/routing/rcaRouting/RcaRoutingPacket.msg.
//

#ifndef _RCAROUTINGPACKET_M_H_
#define _RCAROUTINGPACKET_M_H_

#include <omnetpp.h>

// opp_msgc version check
#define MSGC_VERSION 0x0405
#if (MSGC_VERSION!=OMNETPP_VERSION)
#    error Version mismatch! Probably this file was generated by an earlier version of opp_msgc: 'make clean' should help.
#endif

// cplusplus {{
#include "RoutingPacket_m.h"
// }}



/**
 * Enum generated from <tt>src/node/communication/routing/rcaRouting/RcaRoutingPacket.msg</tt> by opp_msgc.
 * <pre>
 * enum RcaRoutingPacket_Type
 * {
 * 	RCA_ROUTING_ADV_PACKET 	              = 1;		
 * 	RCA_ROUTING_JOIN_PACKET 	          = 2;		
 * 	RCA_ROUTING_TDMA_PACKET 	          = 3;		
 * 	RCA_ROUTING_DATA_PACKET 	          = 4;
 * 	RCA_ROUTING_COMPETECH_PACKET          = 5;
 * 	RCA_ROUTING_FINALHEAD_PACKET          = 6;
 * 	RCA_ROUTING_QUITELECTION_PACKET       = 7;
 * 	RCA_ROUTING_ADJACENTCH_PACKET         = 8;
 * 	RCA_ROUTING_AGGREGATEDADJACENT_PACKET = 9;
 * 	RCA_ROUTING_ROTAT_TDMA_PACKET         = 10;
 * 	RCA_ROUTING_BS_PACKET                 = 11;
 * 	RCA_ROUTING_BROADCAST_BS_PACKET		  = 12;
 * 	RCA_ROUTING_AGGREGATED_BS_PACKET      = 13;
 * 	RCA_ROUTING_HELLO_PACKET              = 14;
 * 	
 * };
 * </pre>
 */
enum RcaRoutingPacket_Type {
    RCA_ROUTING_ADV_PACKET = 1,
    RCA_ROUTING_JOIN_PACKET = 2,
    RCA_ROUTING_TDMA_PACKET = 3,
    RCA_ROUTING_DATA_PACKET = 4,
    RCA_ROUTING_COMPETECH_PACKET = 5,
    RCA_ROUTING_FINALHEAD_PACKET = 6,
    RCA_ROUTING_QUITELECTION_PACKET = 7,
    RCA_ROUTING_ADJACENTCH_PACKET = 8,
    RCA_ROUTING_AGGREGATEDADJACENT_PACKET = 9,
    RCA_ROUTING_ROTAT_TDMA_PACKET = 10,
    RCA_ROUTING_BS_PACKET = 11,
    RCA_ROUTING_BROADCAST_BS_PACKET = 12,
    RCA_ROUTING_AGGREGATED_BS_PACKET = 13,
    RCA_ROUTING_HELLO_PACKET = 14
};

/**
 * Class generated from <tt>src/node/communication/routing/rcaRouting/RcaRoutingPacket.msg</tt> by opp_msgc.
 * <pre>
 * packet RcaRoutingPacket extends RoutingPacket
 * {	
 * 	int RcaRoutingPacketKind enum (RcaRoutingPacket_Type);   
 * 	int schedule[];	
 * 	double x;
 * 	double y;
 * 	double Tn;
 * 	double RComp;
 * 	double ResidualEnergy;
 * 	double BSDistance;
 * 	double Wght;
 * };
 * </pre>
 */
class RcaRoutingPacket : public ::RoutingPacket
{
  protected:
    int RcaRoutingPacketKind_var;
    int *schedule_var; // array ptr
    unsigned int schedule_arraysize;
    double x_var;
    double y_var;
    double Tn_var;
    double RComp_var;
    double ResidualEnergy_var;
    double BSDistance_var;
    double Wght_var;

  private:
    void copy(const RcaRoutingPacket& other);

  protected:
    // protected and unimplemented operator==(), to prevent accidental usage
    bool operator==(const RcaRoutingPacket&);

  public:
    RcaRoutingPacket(const char *name=NULL, int kind=0);
    RcaRoutingPacket(const RcaRoutingPacket& other);
    virtual ~RcaRoutingPacket();
    RcaRoutingPacket& operator=(const RcaRoutingPacket& other);
    virtual RcaRoutingPacket *dup() const {return new RcaRoutingPacket(*this);}
    virtual void parsimPack(cCommBuffer *b);
    virtual void parsimUnpack(cCommBuffer *b);

    // field getter/setter methods
    virtual int getRcaRoutingPacketKind() const;
    virtual void setRcaRoutingPacketKind(int RcaRoutingPacketKind);
    virtual void setScheduleArraySize(unsigned int size);
    virtual unsigned int getScheduleArraySize() const;
    virtual int getSchedule(unsigned int k) const;
    virtual void setSchedule(unsigned int k, int schedule);
    virtual double getX() const;
    virtual void setX(double x);
    virtual double getY() const;
    virtual void setY(double y);
    virtual double getTn() const;
    virtual void setTn(double Tn);
    virtual double getRComp() const;
    virtual void setRComp(double RComp);
    virtual double getResidualEnergy() const;
    virtual void setResidualEnergy(double ResidualEnergy);
    virtual double getBSDistance() const;
    virtual void setBSDistance(double BSDistance);
    virtual double getWght() const;
    virtual void setWght(double Wght);
};

inline void doPacking(cCommBuffer *b, RcaRoutingPacket& obj) {obj.parsimPack(b);}
inline void doUnpacking(cCommBuffer *b, RcaRoutingPacket& obj) {obj.parsimUnpack(b);}


#endif // _RCAROUTINGPACKET_M_H_
