//
// Generated file, do not edit! Created by opp_msgc 4.5 from src/node/communication/routing/rhucRouting/RhucRoutingPacket.msg.
//

#ifndef _RHUCROUTINGPACKET_M_H_
#define _RHUCROUTINGPACKET_M_H_

#include <omnetpp.h>

// opp_msgc version check
#define MSGC_VERSION 0x0405
#if (MSGC_VERSION!=OMNETPP_VERSION)
#    error Version mismatch! Probably this file was generated by an earlier version of opp_msgc: 'make clean' should help.
#endif

// cplusplus {{
#include "RoutingPacket_m.h"
// }}



/**
 * Enum generated from <tt>src/node/communication/routing/rhucRouting/RhucRoutingPacket.msg</tt> by opp_msgc.
 * <pre>
 * enum RhucRoutingPacket_Type
 * {
 * 	RHUC_ROUTING_ADV_PACKET 	= 1;		
 * 	RHUC_ROUTING_JOIN_PACKET 	= 2;		
 * 	RHUC_ROUTING_TDMA_PACKET 	= 3;		
 * 	RHUC_ROUTING_DATA_PACKET 	= 4;
 * 	RHUC_ROUTING_COMPETECH_PACKET = 5;
 * 	RHUC_ROUTING_FINALHEAD_PACKET = 6;
 * 	RHUC_ROUTING_QUITELECTION_PACKET = 7;
 * 	RHUC_ROUTING_ADJACENTCH_PACKET = 8;
 * 	RHUC_ROUTING_AGGREGATEDADJACENT_PACKET = 9;
 * 	RHUC_ROUTING_ROTAT_TDMA_PACKET = 10;
 * };
 * </pre>
 */
enum RhucRoutingPacket_Type {
    RHUC_ROUTING_ADV_PACKET = 1,
    RHUC_ROUTING_JOIN_PACKET = 2,
    RHUC_ROUTING_TDMA_PACKET = 3,
    RHUC_ROUTING_DATA_PACKET = 4,
    RHUC_ROUTING_COMPETECH_PACKET = 5,
    RHUC_ROUTING_FINALHEAD_PACKET = 6,
    RHUC_ROUTING_QUITELECTION_PACKET = 7,
    RHUC_ROUTING_ADJACENTCH_PACKET = 8,
    RHUC_ROUTING_AGGREGATEDADJACENT_PACKET = 9,
    RHUC_ROUTING_ROTAT_TDMA_PACKET = 10
};

/**
 * Class generated from <tt>src/node/communication/routing/rhucRouting/RhucRoutingPacket.msg</tt> by opp_msgc.
 * <pre>
 * packet RhucRoutingPacket extends RoutingPacket
 * {	
 * 	int RhucRoutingPacketKind enum (RhucRoutingPacket_Type);   
 * 	int schedule[];	
 * 	double x;
 * 	double y;
 * 	double RComp;
 * 	double ResidualEnergy;
 * 	double BSDistance;
 * };
 * </pre>
 */
class RhucRoutingPacket : public ::RoutingPacket
{
  protected:
    int RhucRoutingPacketKind_var;
    int *schedule_var; // array ptr
    unsigned int schedule_arraysize;
    double x_var;
    double y_var;
    double RComp_var;
    double ResidualEnergy_var;
    double BSDistance_var;

  private:
    void copy(const RhucRoutingPacket& other);

  protected:
    // protected and unimplemented operator==(), to prevent accidental usage
    bool operator==(const RhucRoutingPacket&);

  public:
    RhucRoutingPacket(const char *name=NULL, int kind=0);
    RhucRoutingPacket(const RhucRoutingPacket& other);
    virtual ~RhucRoutingPacket();
    RhucRoutingPacket& operator=(const RhucRoutingPacket& other);
    virtual RhucRoutingPacket *dup() const {return new RhucRoutingPacket(*this);}
    virtual void parsimPack(cCommBuffer *b);
    virtual void parsimUnpack(cCommBuffer *b);

    // field getter/setter methods
    virtual int getRhucRoutingPacketKind() const;
    virtual void setRhucRoutingPacketKind(int RhucRoutingPacketKind);
    virtual void setScheduleArraySize(unsigned int size);
    virtual unsigned int getScheduleArraySize() const;
    virtual int getSchedule(unsigned int k) const;
    virtual void setSchedule(unsigned int k, int schedule);
    virtual double getX() const;
    virtual void setX(double x);
    virtual double getY() const;
    virtual void setY(double y);
    virtual double getRComp() const;
    virtual void setRComp(double RComp);
    virtual double getResidualEnergy() const;
    virtual void setResidualEnergy(double ResidualEnergy);
    virtual double getBSDistance() const;
    virtual void setBSDistance(double BSDistance);
};

inline void doPacking(cCommBuffer *b, RhucRoutingPacket& obj) {obj.parsimPack(b);}
inline void doUnpacking(cCommBuffer *b, RhucRoutingPacket& obj) {obj.parsimUnpack(b);}


#endif // _RHUCROUTINGPACKET_M_H_
