//
// Generated file, do not edit! Created by opp_msgc 4.5 from src/node/communication/routing/rHeedRouting/RHeedRoutingPacket.msg.
//

#ifndef _RHEEDROUTINGPACKET_M_H_
#define _RHEEDROUTINGPACKET_M_H_

#include <omnetpp.h>

// opp_msgc version check
#define MSGC_VERSION 0x0405
#if (MSGC_VERSION!=OMNETPP_VERSION)
#    error Version mismatch! Probably this file was generated by an earlier version of opp_msgc: 'make clean' should help.
#endif

// cplusplus {{
#include "RoutingPacket_m.h"
// }}



/**
 * Enum generated from <tt>src/node/communication/routing/rHeedRouting/RHeedRoutingPacket.msg</tt> by opp_msgc.
 * <pre>
 * enum RHeedRoutingPacket_Type
 * {
 * 	RHEED_ROUTING_ADV_PACKET 	= 1;		
 * 	RHEED_ROUTING_JOIN_PACKET 	= 2;		
 * 	RHEED_ROUTING_TDMA_PACKET 	= 3;		
 * 	RHEED_ROUTING_DATA_PACKET 	= 4;
 * 	RHEED_ROUTING_NIDV_PACKET   = 5;
 * 	RHEED_ROUTING_RADV_PACKET   = 6;
 * };
 * </pre>
 */
enum RHeedRoutingPacket_Type {
    RHEED_ROUTING_ADV_PACKET = 1,
    RHEED_ROUTING_JOIN_PACKET = 2,
    RHEED_ROUTING_TDMA_PACKET = 3,
    RHEED_ROUTING_DATA_PACKET = 4,
    RHEED_ROUTING_NIDV_PACKET = 5,
    RHEED_ROUTING_RADV_PACKET = 6
};

/**
 * Class generated from <tt>src/node/communication/routing/rHeedRouting/RHeedRoutingPacket.msg</tt> by opp_msgc.
 * <pre>
 * packet RHeedRoutingPacket extends RoutingPacket
 * {	
 * 	int RHeedRoutingPacketKind enum (RHeedRoutingPacket_Type);   
 * 	int schedule[];
 * 	int cost;
 * 	bool status;		
 * };
 * </pre>
 */
class RHeedRoutingPacket : public ::RoutingPacket
{
  protected:
    int RHeedRoutingPacketKind_var;
    int *schedule_var; // array ptr
    unsigned int schedule_arraysize;
    int cost_var;
    bool status_var;

  private:
    void copy(const RHeedRoutingPacket& other);

  protected:
    // protected and unimplemented operator==(), to prevent accidental usage
    bool operator==(const RHeedRoutingPacket&);

  public:
    RHeedRoutingPacket(const char *name=NULL, int kind=0);
    RHeedRoutingPacket(const RHeedRoutingPacket& other);
    virtual ~RHeedRoutingPacket();
    RHeedRoutingPacket& operator=(const RHeedRoutingPacket& other);
    virtual RHeedRoutingPacket *dup() const {return new RHeedRoutingPacket(*this);}
    virtual void parsimPack(cCommBuffer *b);
    virtual void parsimUnpack(cCommBuffer *b);

    // field getter/setter methods
    virtual int getRHeedRoutingPacketKind() const;
    virtual void setRHeedRoutingPacketKind(int RHeedRoutingPacketKind);
    virtual void setScheduleArraySize(unsigned int size);
    virtual unsigned int getScheduleArraySize() const;
    virtual int getSchedule(unsigned int k) const;
    virtual void setSchedule(unsigned int k, int schedule);
    virtual int getCost() const;
    virtual void setCost(int cost);
    virtual bool getStatus() const;
    virtual void setStatus(bool status);
};

inline void doPacking(cCommBuffer *b, RHeedRoutingPacket& obj) {obj.parsimPack(b);}
inline void doUnpacking(cCommBuffer *b, RHeedRoutingPacket& obj) {obj.parsimUnpack(b);}


#endif // _RHEEDROUTINGPACKET_M_H_
