//
// Generated file, do not edit! Created by opp_msgc 4.5 from src/node/communication/routing/mHeedRouting/MHeedRoutingPacket.msg.
//

#ifndef _MHEEDROUTINGPACKET_M_H_
#define _MHEEDROUTINGPACKET_M_H_

#include <omnetpp.h>

// opp_msgc version check
#define MSGC_VERSION 0x0405
#if (MSGC_VERSION!=OMNETPP_VERSION)
#    error Version mismatch! Probably this file was generated by an earlier version of opp_msgc: 'make clean' should help.
#endif

// cplusplus {{
#include "RoutingPacket_m.h"
// }}



/**
 * Enum generated from <tt>src/node/communication/routing/mHeedRouting/MHeedRoutingPacket.msg</tt> by opp_msgc.
 * <pre>
 * enum MHeedRoutingPacket_Type {
 * 	MHEED_ROUTING_ADV_PACKET 	= 1;		
 * 	MHEED_ROUTING_JOIN_PACKET 	= 2;		
 * 	MHEED_ROUTING_TDMA_PACKET 	= 3;		
 * 	MHEED_ROUTING_DATA_PACKET 	= 4;
 * 	MHEED_ROUTING_NIDV_PACKET   = 5;
 * }
 * </pre>
 */
enum MHeedRoutingPacket_Type {
    MHEED_ROUTING_ADV_PACKET = 1,
    MHEED_ROUTING_JOIN_PACKET = 2,
    MHEED_ROUTING_TDMA_PACKET = 3,
    MHEED_ROUTING_DATA_PACKET = 4,
    MHEED_ROUTING_NIDV_PACKET = 5
};

/**
 * Struct generated from src/node/communication/routing/mHeedRouting/MHeedRoutingPacket.msg by opp_msgc.
 */
struct NDInfo
{
    NDInfo();
    int src;
    double eng;
};

void doPacking(cCommBuffer *b, NDInfo& a);
void doUnpacking(cCommBuffer *b, NDInfo& a);

/**
 * Class generated from <tt>src/node/communication/routing/mHeedRouting/MHeedRoutingPacket.msg</tt> by opp_msgc.
 * <pre>
 * packet MHeedRoutingPacket extends RoutingPacket {	
 * 	int MHeedRoutingPacketKind enum (MHeedRoutingPacket_Type);   
 * 	int cost;
 * 	double eng;
 * 	bool status;
 * 	NDInfo clusterMembers[];		
 * }
 * </pre>
 */
class MHeedRoutingPacket : public ::RoutingPacket
{
  protected:
    int MHeedRoutingPacketKind_var;
    int cost_var;
    double eng_var;
    bool status_var;
    NDInfo *clusterMembers_var; // array ptr
    unsigned int clusterMembers_arraysize;

  private:
    void copy(const MHeedRoutingPacket& other);

  protected:
    // protected and unimplemented operator==(), to prevent accidental usage
    bool operator==(const MHeedRoutingPacket&);

  public:
    MHeedRoutingPacket(const char *name=NULL, int kind=0);
    MHeedRoutingPacket(const MHeedRoutingPacket& other);
    virtual ~MHeedRoutingPacket();
    MHeedRoutingPacket& operator=(const MHeedRoutingPacket& other);
    virtual MHeedRoutingPacket *dup() const {return new MHeedRoutingPacket(*this);}
    virtual void parsimPack(cCommBuffer *b);
    virtual void parsimUnpack(cCommBuffer *b);

    // field getter/setter methods
    virtual int getMHeedRoutingPacketKind() const;
    virtual void setMHeedRoutingPacketKind(int MHeedRoutingPacketKind);
    virtual int getCost() const;
    virtual void setCost(int cost);
    virtual double getEng() const;
    virtual void setEng(double eng);
    virtual bool getStatus() const;
    virtual void setStatus(bool status);
    virtual void setClusterMembersArraySize(unsigned int size);
    virtual unsigned int getClusterMembersArraySize() const;
    virtual NDInfo& getClusterMembers(unsigned int k);
    virtual const NDInfo& getClusterMembers(unsigned int k) const {return const_cast<MHeedRoutingPacket*>(this)->getClusterMembers(k);}
    virtual void setClusterMembers(unsigned int k, const NDInfo& clusterMembers);
};

inline void doPacking(cCommBuffer *b, MHeedRoutingPacket& obj) {obj.parsimPack(b);}
inline void doUnpacking(cCommBuffer *b, MHeedRoutingPacket& obj) {obj.parsimUnpack(b);}


#endif // _MHEEDROUTINGPACKET_M_H_
